name: Bienvenida!

on:
  push:
    branches:
      - main

jobs:
  saludo_job:
    runs-on: windows x64
    steps:
      - name: Saludar
        run: |
          echo "Hola Github Actions!!!"

      - name: Print Date
        run: |
          echo "The current date is $(date +"%B %d, %Y")"

      - name: List Files
        run: ls -l

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: npm install
        run: npm install

      - name: lint
        run: npm run eslint