name: Bienvenida!

on:
  push:
    branches:
      - main

jobs:
  saludo_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Saludar
        run: |
          echo "Hola Github Actions!!!"

      - name: Print Date
        run: |
          echo "The current date is $(date +"%B %d, %Y")"

      - name: List Files
        run: ls -l